name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-react:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1

      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        touch .env
        echo SKIP_PREFLIGHT_CHECK=true >> .env
        echo REACT_APP_API_URL='http://0.0.0.0:8000' >> .env
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./frontend/build


  build:
    needs: build-react
    runs-on: ubuntu-latest

  
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: build
        path: ./backend/
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker-compose build 
    - name: Docker Tag
      run: docker tag test_project ${{secrets.DOCKER_USERNAME}}/test
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USERNAME}}/test
      
